import type { UserFacingError } from "./types";

export type ErrorCatalogEntry = Omit<UserFacingError, "raw" | "debugMessage" | "httpStatus">;

export const ERROR_CATALOG = {
  unknown: {
    code: "unknown_error",
    category: "unknown",
    severity: "error",
    title: "操作失败",
    message: "遇到了一点问题，请稍后重试。",
    action: "retry",
    actionLabel: "重试",
  },
  server: {
    code: "server_error",
    category: "server",
    severity: "error",
    title: "服务暂时不可用",
    message: "服务暂时不可用，请稍后重试。",
    action: "retry",
    actionLabel: "重试",
  },
  network: {
    code: "network_error",
    category: "network",
    severity: "error",
    title: "网络连接异常",
    message: "网络连接不稳定，请检查网络后重试。",
    action: "retry",
    actionLabel: "重试",
  },
  timeout: {
    code: "timeout",
    category: "timeout",
    severity: "error",
    title: "请求超时",
    message: "处理时间较长，请稍后重试。",
    action: "retry",
    actionLabel: "重试",
  },
  rateLimit: {
    code: "rate_limit",
    category: "rate_limit",
    severity: "warning",
    title: "请求过于频繁",
    message: "当前模型请求较多，请稍后重试或切换模型。",
    action: "switch_model",
    actionLabel: "切换模型",
  },
  quota: {
    code: "quota_insufficient",
    category: "quota",
    severity: "warning",
    title: "额度不足",
    message: "当前额度不足，请更换模型或稍后重试。",
    action: "switch_model",
    actionLabel: "更换模型",
  },
  loginRequired: {
    code: "login_required",
    category: "auth",
    severity: "warning",
    title: "需要登录",
    message: "请先登录后继续使用。",
    action: "login",
    actionLabel: "去登录",
  },
  fileTooLarge: {
    code: "file_too_large",
    category: "file",
    severity: "warning",
    title: "文件过大",
    message: "文件超过大小限制，请压缩后重新上传。",
    action: "reduce_file",
    actionLabel: "重新上传",
  },
  fileUnsupported: {
    code: "file_unsupported",
    category: "file",
    severity: "warning",
    title: "文件格式不支持",
    message: "文件格式不支持，请换一个文件上传。",
    action: "upload_again",
    actionLabel: "重新上传",
  },
  contentPolicy: {
    code: "content_policy",
    category: "content_policy",
    severity: "warning",
    title: "内容无法生成",
    message: "当前内容可能不符合生成规则，请调整描述后重试。",
    action: "adjust_prompt",
    actionLabel: "调整描述",
  },
} satisfies Record<string, ErrorCatalogEntry>;
